In [17]:
# DEPENDENCIES
import sqlite3
import csv
import re
import sklearn
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
import time
import numpy as np
import matplotlib.pyplot as plt
# import seaborn as sns

In [18]:
def text_preprocessing(
    token:str,
    punctuations = r'''!()-[]{};:‘'’"\,<>./?@#$%^&*_“~''')->list:
    # print(token)
    token = re.sub(r"""[()\"#/@;:.<>{}`––‘+«’%-=~|!?"“”,']""", "", token)
    token = re.sub(r'[0-9]+','',token)
    token = re.sub("[A-Za-z]","",token)
    token = re.sub(" +"," ", token)
    return token

# getting embedding_dict from tfidf vectoriser with dimensions
max_dim = 50
from sklearn.feature_extraction.text import TfidfVectorizer

# lines_with_value_1 = ["sky sun green what blue","sun yellow bright what"]
list_of_lines_as_strings = []
tags_for_tfidf = []

def tokenize(text:str)->list:
    return (text.split())
with open('/home/balu/cl2/project/datasets/telugu/telugu-dataset-rohit.csv', 'r') as total_file:
    data = csv.reader(total_file)
    # for i in range(1,):
    next(data)
    for line in (data):
    # for (line,i) in zip(data,range(1,100,1)):
        line_string = ''
        for k in reversed(line):
            if(k==''):
                del line[-1:]
            else:
                break
        i = len(line)
        # print(line)
        k = (line[i-2],line[i-1])
        # print(k)
        del line[-2:]
        tags_for_tfidf.append(k)
        for cell in line:
            for token in cell:
                processed_token = text_preprocessing(token)
                # in case of morphology just append the root word from the dictionary
                # if the word doesn't exist in dict then there is a reason in morphological analysis
                # in that case just avoid it.
                if(processed_token != ''):
                    line_string += processed_token
        list_of_lines_as_strings.append(line_string)
print(len(list_of_lines_as_strings))
y_tfidf = []
index = 0
count_temp = 0
for a in tags_for_tfidf:
    labell = a[0].strip()
    if(labell == "TRS"):
        index = 1
    elif(labell == "BJP"):
        index = 2
    elif(labell == "YCP"):
        index = 3
    elif(labell == "TDP"):
        index = 4
    elif(labell == "Congress"):
        index = 5
    else:
        index = 0
    y_tfidf.append(index)
vectoriser = TfidfVectorizer(max_features = max_dim,vocabulary = None,tokenizer = tokenize)
tfidf_vectors_for_all_text = vectoriser.fit(list_of_lines_as_strings)
tfidf_vectors_for_all_text = vectoriser.transform(list_of_lines_as_strings)
# print(tfidf_vectors_for_all_text.get_shape())

1325


/home/balu/.local/lib/python3.8/site-packages/sklearn/feature_extraction/text.py:524: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [19]:
#for tfidf
# TRAININIG MULTINOMIAL AND TESTING IT
import seaborn as sns

def model_Evaluate(model):
    # Predict values for Test dataset
    y_pred = model.predict(X_test)
    # Print the evaluation metrics for the dataset.
    print(classification_report(y_test, y_pred))
    # Compute and plot the Confusion matrix
    cf_matrix = confusion_matrix(y_test, y_pred,)
    print(cf_matrix)

X_train, X_test, y_train, y_test = train_test_split(tfidf_vectors_for_all_text, y_tfidf, test_size=0.2, random_state=8)
# print(X_test,y_test)
BNBmodel = MultinomialNB()
start = time.time()
BNBmodel.fit(X_train, y_train)
end = time.time()
# print("The execution time of this model is {:.2f} seconds\n".format(end-start))
model_Evaluate(BNBmodel)
y_pred1 = BNBmodel.predict(X_test)


              precision    recall  f1-score   support

           0       0.54      0.68      0.60        37
           1       0.90      0.56      0.69        32
           2       0.70      0.61      0.65        38
           3       0.79      0.73      0.76        75
           4       0.52      0.75      0.62        65
           5       1.00      0.11      0.20        18

    accuracy                           0.65       265
   macro avg       0.74      0.57      0.59       265
weighted avg       0.70      0.65      0.64       265

[[25  0  2  3  7  0]
 [ 2 18  1  1 10  0]
 [ 7  0 23  0  8  0]
 [ 3  0  0 55 17  0]
 [ 3  1  1 11 49  0]
 [ 6  1  6  0  3  2]]
